# Generated by Django 4.2.5 on 2023-09-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'Currency value',
                'verbose_name_plural': 'Currency values',
            },
        ),
        migrations.CreateModel(
            name='CurrencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=3)),
                ('currency_values', models.ManyToManyField(related_name='currency_values', to='currency.currencyvalue')),
            ],
            options={
                'verbose_name': 'Currency names',
                'verbose_name_plural': 'Currency name',
            },
        ),
        migrations.CreateModel(
            name='CurrencyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('currency_names', models.ManyToManyField(related_name='currency_dates', to='currency.currencyname')),
            ],
            options={
                'verbose_name': 'Currency date',
                'verbose_name_plural': 'Currency dates',
            },
        ),
    ]
